definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.OrderPayload:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  models.ProductPayload:
    properties:
      name:
        type: string
      quantity:
        type: integer
      unit:
        type: string
    required:
    - name
    - quantity
    type: object
info:
  contact: {}
  description: САМЫЙ АХУЕННЫЙ СЕРВИС ДЛЯ РАБОТЫ С 1С
  title: 1C API
  version: "13.37"
paths:
  /api/v1/{id}/:
    get:
      consumes:
      - application/json
      description: Get all products associated with an order
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Order not found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get products by order ID
      tags:
      - products
  /api/v1/{id}/add:
    post:
      consumes:
      - application/json
      description: Add a new product to an order
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Payload
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.ProductPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Product successfully added
          schema:
            type: string
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Validation errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Failed to add product
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Add a new product
      tags:
      - products
  /api/v1/create:
    post:
      consumes:
      - application/json
      description: Create a new order with the input payload
      parameters:
      - description: Order Payload
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/models.OrderPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Order successfully created
          schema:
            type: string
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Validation errors
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Failed to create order
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new order
      tags:
      - orders
swagger: "2.0"
